FROM nginx
LABEL https://github.com/ceerlepy, https://github.com/ceerlepy
COPY /nginx.conf	/etc/nginx/nginx.conf
#COPY /server.crt	/etc/nginx/server.crt
#COPY /server.key	/etc/nginx/server.key
COPY /static	    /static
